import type { Metadata } from "next";
import "./globals.css";
import AuthContextProvider from "./context/AuthContextProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`flex h-screen`}>
				<div className="flex-1 p-5">
					<AuthContextProvider>
						<Toaster />
						{children}
					</AuthContextProvider>
				</div>
			</body>
		</html>
	);
}
